apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"  # Set the CPU limit to 0.5 CPU cores
            memory: "512Mi"  # Set the memory limit to 512 MiB
          requests:
            cpu: "0.1"  # Set the CPU request to 0.1 CPU cores
            memory: "128Mi"  # Set the memory request to 128 MiB
