apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "2"     # Updated CPU limit to 1 CPU core
            memory: "2Gi"  # Updated memory limit to 1 GiB
          requests:
            cpu: "0.5"   # Updated CPU request to 0.2 CPU cores
            memory: "1Gi"  # Updated memory request to 256 MiB
