name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Apply Terraform Changes
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Configure AWS CLI
        run: |
          aws eks update-kubeconfig --name my-cluster --region eu-central-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/nginx-deployment.yaml
          kubectl apply -f kubernetes/nginx-service.yaml
